### PR TITLE
Fix cookstyle offenses

### PR DESCRIPTION
**Pull request by shortdudey123**
### Description
Cleans up the cookstyle errors that are showing up in travis

### Issues Resolved

travis testing

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by tas50** [comment]
@shortdudey123 Still seeing failures in Travis

**Comment by shortdudey123** [comment]
Thought i had gotten those too, should pass now :)

**Comment by shortdudey123** [comment]
Travis failing due to not being able to install chefdk

**Comment by tas50** [comment]
This will clear up when the new DK hits current or we switch from move to copies

**Pull request merged**
